### ISSUE TITLE
Sell from multiple buy order return error 

### ISSUE THREAD

**Issue by Dinaamagdy** [rivine/recordchain#36]
## Steps 
- Create three similar buy order as shown everyone it's mount=100:
```
x.order_book.add_buy_order(price_max='10 ETH', currency_to_buy='BTC', currency_mine=['USD','EGP'], amount=100, expiration=j.data.time.epoch + 1000, approved=True)
x.order_book.add_buy_order(price_max='10 ETH', currency_to_buy='BTC', currency_mine=['USD'], amount=100, expiration=j.data.time.epoch + 1000, approved=True)
x.order_book.add_buy_order(price_max='10 ETH', currency_to_buy='BTC', currency_mine=['USD'], amount=100, expiration=j.data.time.epoch + 1000, approved=True)
```
- Create sell order accept same currency as buy orders with mount= 200 , as shown 
"""
x.order_book.add_sell_order(price_min='10 XRP', currency_to_sell='BTC' ,currency_accept=['USD'], amount=200, expiration=j.data.time.epoch + 1000, approved=True)
"""

## Issue 
- it result the following error : 
```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/opt/code/github/rivine/recordchain/JumpScale9RecordChain/apps/orderbook/lib/trader.py", line 101, in _consume
    self.process(transaction)
  File "/opt/code/github/rivine/recordchain/JumpScale9RecordChain/apps/orderbook/lib/trader.py", line 90, in process
    self._post_success(transaction)
  File "/opt/code/github/rivine/recordchain/JumpScale9RecordChain/apps/orderbook/lib/trader.py", line 56, in _post_success
    if self.matcher.approved_sell_orders[sell_index]['amount'] == 0:
TypeError: list indices must be integers or slices, not NoneType
2018-07-02T16:34:50Z <Greenlet "Greenlet-0" at 0x7f6a28988e48: <bound method Trader._consume of <orderbook.lib.trader.Trader object at 0x7f6a28911390>>> failed with TypeError

```
- the buy order don't work corectly as shown 
```
TYPE     id      AMOUNT  PRICE
SELL     1       0       10.0 XRP
BUY      3       0       10.0 ETH
BUY      2       0       10.0 ETH
BUY      1       100.0   10.0 ETH

```

**Comment by andrewayoub** [comment]
fixed in 9ba078f3e2d1230e5f8c45dd1df12adc2905ad5b
